### ISSUE TITLE
Marching cubes missing

### ISSUE THREAD

**Issue by DeltaMarine101** [nihalsid/retrieval-fuse#3]
Hi, the utils/marching_cubes file is missing from this repo, making  `import marching_cubes as mc` fail. I can see that "util/marching_cubes/*.pyd" is included in the .gitgnore, so would it be possible to provide this file, or let me know what marching cubes implementation this project requires?

Thanks!

**Comment by nihalsid** [comment]
Hi, the marching cubes implementation we were using was the one from here: https://github.com/JustusThies/PyMarchingCubes

**Comment by DeltaMarine101** [comment]
Awesome, thank you!
